# Generated by Django 5.0.6 on 2025-05-29 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='besties',
            field=models.ManyToManyField(blank=True, related_name='bestie_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
