# Generated by Django 5.0.6 on 2025-05-29 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_customuser_blocked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='blocked_users',
        ),
    ]
