# Generated by Django 5.0.6 on 2025-06-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_customuser_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='iv',
            field=models.TextField(blank=True, null=True),
        ),
    ]
