# Generated by Django 5.0.6 on 2025-06-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_chatmessage_iv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='iv',
        ),
    ]
