# Generated by Django 5.0.6 on 2025-09-02 16:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_post_like_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='is_read',
            new_name='seen',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
